### ISSUE TITLE
Contao 4.9 support

### ISSUE THREAD

**Issue by salteax** [hschottm/textwizard#4]
Hi, with version 3.4 you allowed php 8, but also raised the contao dependency without any code changes to 4.13. So your bundle is not usable with contao 4.9 and php 8. Would it be possible to also allow contao 4.9?

**Comment by Total-Reality** [comment]
Thanks, hat would be nice...
I don't understand why some developers have a so cruel update policy with this strict settings of the core dependencies in the composer.json in some extensions, if it is already working with Contao 4.9...

https://github.com/pdir/contao-survey/issues/24
